---
title: "problm"
author: "rhadoop"
date: "2019년 3월 13일"
output: 
  word_document: default
  github_document: default
  pdf_document: 
    latex_engine: xelatex
  html_document: default
  html_notebook: default  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

### 문제 1. ggplot2 의 midwest 데이터를 데이터 프레임 형태로 불러와서 데이터의 특성을 파악하세요.
```{r}
library(dplyr)
library(ggplot2)

df_midwest = as.data.frame(ggplot2::midwest)
head(df_midwest)
tail(df_midwest)
View(df_midwest)
dim(df_midwest)
str(df_midwest)
summary(df_midwest)
```
### 문제 2. poptotal(전체 인구)을 total 로, popasian(아시아 인구)을 asian 으로 변수명을 수정하세요.
```{r}
df_midwest <- rename(df_midwest, total = poptotal, asian=popasian)
head(df_midwest)
```

### 문제 3. total, asian 변수를 이용해 '전체 인구 대비 아시아 인구 백분율' 파생변수를 만들고, 히스토그램을 만들어 도시들이 어떻게 분포하는지 살펴보세요.
```{r}
df_midwest$p_asian = (df_midwest$asian /df_midwest$total) *100
qplot(df_midwest$state,df_midwest$p_asian, data=df_midwest, geom="auto")
```
### 문제 4. 아시아 인구 백분율 전체 평균을 구하고, 평균을 초과하면 "large", 그 외에는 "small"을 부여하는 파생변수를 만들어 보세요.
```{r}
avg=mean(df_midwest$p_asian)
df_midwest$grade = ifelse(df_midwest$p_asian>=avg,"large","small")

```
                  
### 문제 5. "large"와 "small"에 해당하는 지역이 얼마나 되는지, 빈도표와 빈도 막대 그래프를 만들어 확인해 보세요
```{r}
table(df_midwest$grade)
qplot(df_midwest$grade)
```


