---
title: "Q3"
author: "rhadoop"
date: "2019년 3월 19일"
output: 
  word_document: default
  github_document: default
  pdf_document: 
    latex_engine: xelatex
  html_document: default
  html_notebook: default  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

#### 문제 2. 미성년 인구 백분율이 가장 높은 상위 5 개 county(지역)의 미성년 인구 백분율을 출력하세요. 

```{r}
library(tidyverse)
library(sqldf)
midwest=as.data.frame(ggplot2::midwest)
```

### dplyr
```{r}
mid_df <- midwest %>%
    mutate(ratio_child = (poptotal-popadults)/poptotal*100) 

mid_df %>% select(county,ratio_child) %>% 
           mutate(grade=ifelse(ratio_child>=40,'large',
                               ifelse(ratio_child<30,'small','middle'))) %>% 
           group_by(grade) %>% 
           summarise(n=n())
```
### sqldf
```{r}
sqldf("select *, (poptotal-popadults)/(poptotal*1.)*100 as ratio_child
          from midwest
          ")  ->sql_df

sqldf("select grade, count(*) as n
          from (
                 select ratio_child, 
                    case 
                     when ratio_child >= 40 then 'large'
                     when ratio_child < 30 then 'small'
                     else 'middle'
                    end as grade   
                 from sql_df)
          group by grade
      ")

```
### R
```{r}
midwest$ratio_child = (midwest$poptotal-midwest$popadults)/midwest$poptotal*100

midwest$grade = ifelse(midwest$ratio_child>=40,'large',
                      ifelse(midwest$ratio_child<30,'small','middle'))

v_grade=unique(midwest$grade)

for (grade in v_grade) {
     group_temp=midwest[midwest$grade==grade,"grade"]
    n=length(group_temp)
    group_temp=data.frame(grade,n)
    if (which(v_grade==grade)==1)
        result =group_temp
    else
        result= rbind(result,group_temp)
  }
result
```