---
title: "Q4"
author: "rhadoop"
date: "2019년 3월 19일"
output: 
  word_document: default
  github_document: default
  pdf_document: 
    latex_engine: xelatex
  html_document: default
  html_notebook: default  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

#### 문제 2. 미성년 인구 백분율이 가장 높은 상위 5 개 county(지역)의 미성년 인구 백분율을 출력하세요. 

```{r}
library(tidyverse)
library(sqldf)
midwest=as.data.frame(ggplot2::midwest)
```

### dplyr
```{r}
midwest %>% mutate(ratio_asian=popasian/poptotal*100) %>% 
    arrange(ratio_asian) %>% 
    select(state,county,ratio_asian) %>% 
    head(10) 
```
### sqldf
```{r}
sqldf("
      select state, county, popasian/(poptotal*1.)*100 as ratio_asian 
             from midwest
             order by ratio_asian
             limit 10
      ")
```
### R
```{r}
midwest$ratio_asian = midwest$popasian/midwest$poptotal*100
head(midwest[order(midwest$ratio_asian),c("state", "county","ratio_asian")],10)
```